In [1]:
import pandas as pd

from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

data = fetch_california_housing(as_frame=True)

X = data.frame[["MedInc"]]
y = data.frame["MedHouseVal"]

poly = PolynomialFeatures(degree=2, include_bias=False)

X_poly = poly.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_poly,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)

result = pd.DataFrame({
    "Модель": ["Polynomial Regression"],
    "Ступінь": [2],
    "R²": [r2]
})

display(result)

                  Модель  Ступінь        R²
0  Polynomial Regression        2  0.463318

In [2]:
import pandas as pd

from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

data = fetch_california_housing(as_frame=True)

X = data.frame[["MedInc"]]
y = data.frame["MedHouseVal"]

results = []

for degree in [1, 2, 3]:

    poly = PolynomialFeatures(
        degree=degree,
        include_bias=False
    )

    X_poly = poly.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(
        X_poly,
        y,
        test_size=0.2,
        random_state=42
    )

    model = LinearRegression()

    model.fit(X_train, y_train)

    train_r2 = r2_score(
        y_train,
        model.predict(X_train)
    )

    test_r2 = r2_score(
        y_test,
        model.predict(X_test)
    )

    results.append([
        degree,
        train_r2,
        test_r2
    ])

result_table = pd.DataFrame(
    results,
    columns=[
        "Ступінь полінома",
        "R² поїзд",
        "Тест R²"
    ]
)

display(result_table)

   Ступінь полінома  R² поїзд   Тест R²
0                 1  0.476993  0.458859
1                 2  0.481598  0.463318
2                 3  0.490806  0.467116